#!/usr/bin/env bash

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# """
# Build and copy the mcp server binary to the script location
# """
WORKSPACE_ROOT="${BUILD_WORKSPACE_DIRECTORY}"
readonly WORKSPACE_ROOT

bazel build //tools/mcp/server

mkdir -p "${WORKSPACE_ROOT}/tools/mcp/ez-mcp"
cp -f \
  "${WORKSPACE_ROOT}/bazel-bin/tools/mcp/server/server" \
  "${WORKSPACE_ROOT}/tools/mcp/server/ez-build-fix.toml" \
  "${WORKSPACE_ROOT}/tools/mcp/ez-mcp"
