// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package enforcer.v2;

// Each Isolate is uniquely identified by the name and publisher of the Isolate.
message IsolateType {
  // The name of the isolate as chosen by the publisher.
  string isolate_name = 1;
  // Must match the publisher_id in the Isolate package endorsement.
  string publisher_id = 2;
}
