// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package enforcer.v2;

import "enforcer/v2/common.proto";
import "enforcer/v2/ez_backend_dependencies.proto";
import "enforcer/v2/ez_service_spec.proto";
import "enforcer/v2/isolate_metrics_policy.proto";
import "enforcer/v2/isolate_startup_parameters.proto";

// Describes an Opaque Isolate manifest containing a list of
// OpaqueIsolateDescriptors.
message OpaqueIsolateManifest {
  repeated OpaqueIsolateDescriptor opaque_isolate_descriptors = 1;
}

// Describes a binary to be run inside an Opaque Isolate, and the services that
// Isolate will expose.
message OpaqueIsolateDescriptor {
  // Unique identification of the isolate by name and publisher.
  IsolateType isolate_type = 1;
  // An arbitrary but unique filename (POSIX-compatible) to use for this
  // package. The filename is how other packages will expect to find this
  // package in a bundle.
  //
  // Example: acme.com-ads-backend1-v1.09012024.3.ezpkg
  string package_filename = 2;
  // Filename of this executable binary file
  string binary_filename = 3;

  // Specifications for any services this binary implements (not all services
  // may be active at runtime)
  repeated EzServiceSpec service_specs = 4;
  // Specifications for backend services or endpoints outside or inside EZ
  // that this isolate depends on and is permitted to communicate with.
  repeated EzBackendDependency ez_backend_dependencies = 5;
  // Policy that defines which metrics are allowed to be exported by the isolate.
  // If unset, no metrics are exported.
  IsolateMetricsPolicy metrics_policy = 6;

  // TODO: IsolateStartupParameters is temporarily included here before the
  // Package Manager implements a separate RPC to supply dynamic startup parameters.
  IsolateStartupParameters startup_parameters = 7;
}
